name: atlasmart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  intl: ^0.20.2
  mockito: ^5.6.1
  pin_code_fields: ^8.0.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.10.4
  freezed: ^3.2.3
 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/atlasmart_logo1.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
